Core_ProjeGerçek/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntitiyLayer.Concreate;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Core_ProjeGerçek.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SkillController : Controller
    {
        SkillManager skm = new SkillManager(new EfSkillDal());
        public IActionResult Index()
        {
            ViewBag.d1 = "Yetenek Listem";
            ViewBag.d2 = "Anasayfa";
            ViewBag.d3 = "Yetenek Sayfası";
            var values = skm.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.d1 = "Yetenek Ekleme Formu";
            ViewBag.d2 = "Yetenekler";
            ViewBag.d3 = "Yetenek Ekleme Sayfası";
            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill p) 
        {
            skm.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveSkill(int id)
        {
            var deger=skm.GetByID(id);
            skm.TDelete(deger);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult UpdateSkill(int id) 
        {
            ViewBag.d1 = "Yetenek Güncelleme Formu";
            ViewBag.d2 = "Yetenekler";
            ViewBag.d3 = "Yetenek Güncelleme Sayfası";
            var deger = skm.GetByID(id);
            return View(deger);
        }
        [HttpPost]
        public IActionResult UpdateSkill(Skill p)
        {
            skm.Update(p);
            return RedirectToAction("Index");
        }
    
    }
}

Core_ProjeGerçek/Views/Skill/AddSkill.cshtml
@using EntitiyLayer.Concreate

@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Proje Ekleme Formu</h4>
<form method="post" class="m-5">
    <label> Yetenek Başlığı</label>
    <input type="text" name="Title" class="form-control"/>
    <label class="mt-3"> Seviye </label>
    <input type="text" name="Value" class="form-control" />
    <button href="#" class="btn btn-success mt-3">Ekle </button>
</form>

        </div>

    </div>

</div>

Core_ProjeGerçek/Views/Skill/Index.cshtml
@using EntitiyLayer.Concreate
@model List<Skill>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
@{
    string renk = "";
}


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deneyimlerim</h4>
           
            <div class="table-responsive">
                <table class="table">
                    <thead >
            <tr>
                <th >#</th>
                <th >Başlık</th>
                <th>Oran</th>
                <th >Sil</th>
                <th >Düzenle</th>
               
            </tr>
        </thead>
        <tbody class="list">
            @foreach(var x in Model){
                if (Convert.ToInt32(x.Value) >= 0 && Convert.ToInt32(x.Value) <= 50)
                {
                    renk = "progress-bar bg-danger";
               
                }
                if (Convert.ToInt32(x.Value) >= 51 && Convert.ToInt32(x.Value) <= 70)
                {
                    renk = "progress-bar bg-warning";
                   
                }
                if (Convert.ToInt32(x.Value) >= 71 && Convert.ToInt32(x.Value) <= 84)
                {
                    renk = "progress-bar bg-primary";
                   
                }
                if (Convert.ToInt32(x.Value) >= 85 && Convert.ToInt32(x.Value) <= 100)
                {
                    renk = "progress-bar bg-success";
                   
                }
            <tr>
                <th >
                      @x.SkillID
                   
                </th>
                <td class="budget">
                    <span class="name mb-0 text-sm">@x.Title</span>
                </td>
                <td>
                    <div class="d-flex align-items-center">
                        <span class="completion mr-2">@x.Value %</span>
                        <div>
                            <div class="progress">
                                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: @x.Value%;"></div>
                            </div>
                        </div>
                        </div>
                </td>
            
                <td>
                    <a href="/Skill/RemoveSkill/@x.SkillID" class="btn btn-danger">Sil</a>
                </td>
                <td >
                        <a href="/Skill/UpdateSkill/@x.SkillID"  class="btn btn-info">Güncelle</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <a href="/Skill/AddSkill" class="btn btn-primary m-3">Yeni Yetenek Ekle</a>
</div>
        </div>

    </div>

</div>

Core_ProjeGerçek/Views/Skill/UpdateSkill.cshtml
@model EntitiyLayer.Concreate.Skill
@{
    ViewData["Title"] = "UpdateSkill";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Proje Ekleme Formu</h4>
@using (Html.BeginForm("UpdateSkill", "Skill", FormMethod.Post, new { @class = "m-5" }))
{
       
      
        @Html.HiddenFor(x=>x.SkillID)
        @Html.Label("Yetenek Başlığı")
        @Html.TextBoxFor(x=>x.Title, new {@class="form-control mb-2"})
        @Html.Label("Yetenek Değeri")
        @Html.TextBoxFor(x=>x.Value, new {@class="form-control mb-2"})
        <button href="#" class="btn btn-success mt-3">Güncelle </button>
    


}
</div>

        </div>

    </div>